# Generated by Django 4.0.3 on 2022-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='note',
            field=models.FloatField(default=0),
        ),
    ]
